import * as THREE from './three.module.js';
import { GLTFLoader } from './GLTFLoader.js';
import { OrbitControls } from './OrbitControls.js';

const MODELS={
  agv:{file:'./AGV_Robot.glb',label:'AGV · Material Transport',controls:[['WHEEL_LEFT_ROTATE_X','좌측 구동 바퀴','rotation.x',-360,360,0],['WHEEL_RIGHT_ROTATE_X','우측 구동 바퀴','rotation.x',-360,360,0],['03_LIFT_PLATFORM','승강 적재판','position.y',0,.12,0],['LIDAR_ROTATE_Y','라이다','rotation.y',-360,360,0]]},
  amr:{file:'./AMR_Robot.glb',label:'AMR · Autonomous Mobile',controls:[['WHEEL_LEFT_ROTATE_X','좌측 구동 바퀴','rotation.x',-360,360,0],['WHEEL_RIGHT_ROTATE_X','우측 구동 바퀴','rotation.x',-360,360,0],['03_PAYLOAD_DECK','승강 적재 데크','position.y',0,.1,0],['LIDAR_FRONT_ROTATE_Y','전방 라이다','rotation.y',-360,360,0],['LIDAR_REAR_ROTATE_Y','후방 라이다','rotation.y',-360,360,0]]},
  arm:{file:'./ATM_Robot.glb',label:'ATM ARM · Wafer Handling',controls:[['ROBOT_Z_LIFT','승강축','position.y',0,.25,0],['ROBOT_J1_SHOULDER','어깨 관절','rotation.y',-130,130,0],['ROBOT_J2_ELBOW','팔꿈치 관절','rotation.y',-150,150,0],['ROBOT_J3_WRIST','손목 관절','rotation.y',-180,180,0]]}
};
const canvas=document.querySelector('#viewport'),renderer=new THREE.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;
const scene=new THREE.Scene();scene.background=new THREE.Color('#0a181f');const camera=new THREE.PerspectiveCamera(42,1,.01,100);const orbit=new OrbitControls(camera,canvas);orbit.enableDamping=true;orbit.target.set(0,.25,0);camera.position.set(1.9,1.45,2.25);orbit.update();
scene.add(new THREE.HemisphereLight(0xa9e9ef,0x15252d,2.5));const key=new THREE.DirectionalLight(0xd9fbff,3.5);key.position.set(3,5,4);scene.add(key);const fill=new THREE.DirectionalLight(0x5ccbd2,1.7);fill.position.set(-4,2,-2);scene.add(fill);const grid=new THREE.GridHelper(12,24,0x31606a,0x17313a);grid.material.opacity=.65;grid.material.transparent=true;scene.add(grid);const plane=new THREE.Mesh(new THREE.PlaneGeometry(12,12),new THREE.MeshStandardMaterial({color:0x0b1b21,roughness:.9,metalness:.15}));plane.rotation.x=-Math.PI/2;plane.position.y=-.006;scene.add(plane);
const loader=new GLTFLoader();let current=null,currentType='agv',nodes=new Map(),defaults=new Map();const el=id=>document.querySelector(id);const status=el('#load-status'),loaderEl=el('#loader'),controlsEl=el('#controls');
function resize(){const r=canvas.getBoundingClientRect();renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix()}addEventListener('resize',resize);resize();
function findNodes(root){nodes=new Map();defaults=new Map();root.traverse(n=>{if(n.name){nodes.set(n.name,n);defaults.set(n.uuid,{position:n.position.clone(),rotation:n.rotation.clone(),quaternion:n.quaternion.clone()})}})}
function controlUI(type){controlsEl.innerHTML='';for(const [node,label,path,min,max,value] of MODELS[type].controls){const row=document.createElement('div');row.className='control-row';row.innerHTML=`<div class="control-head"><span>${label}</span><output>${value}</output></div><input type="range" min="${min}" max="${max}" step="${max>1?1:.01}" value="${value}" aria-label="${label}">`;const input=row.querySelector('input'),out=row.querySelector('output');input.addEventListener('input',()=>{const n=nodes.get(node),v=Number(input.value);out.textContent=max>1?`${v}°`:`${v.toFixed(2)}m`;if(!n)return;const [group,prop]=path.split('.');n[group][prop]=max>1?THREE.MathUtils.degToRad(v):(defaults.get(n.uuid)[group][prop]+v)});controlsEl.append(row)}}
async function load(type){currentType=type;loaderEl.classList.remove('hidden');status.textContent='GLB 불러오는 중';if(current){scene.remove(current);current=null}try{const gltf=await loader.loadAsync(MODELS[type].file);current=gltf.scene;findNodes(current);scene.add(current);controlUI(type);el('#model-name').textContent=MODELS[type].label;el('#model-meta').textContent=`${nodes.size}개 노드 · ${MODELS[type].controls.length}개 조작 부품`;status.textContent='모델 준비 완료';loaderEl.classList.add('hidden');resetModel();}catch(error){console.error(error);status.textContent='모델 로드 실패';loaderEl.textContent='GLB 파일을 찾을 수 없습니다';}}
function resetModel(){if(!current)return;current.position.set(0,0,0);for(const n of nodes.values()){const d=defaults.get(n.uuid);n.position.copy(d.position);n.rotation.copy(d.rotation)}for(const input of controlsEl.querySelectorAll('input')){input.value=input.defaultValue;input.dispatchEvent(new Event('input'))}for(const axis of ['x','y','z']){el(`#pos-${axis}`).value=0;el(`#${axis}-output`).textContent='0.00'}}
for(const axis of ['x','y','z']){const input=el(`#pos-${axis}`);input.addEventListener('input',()=>{if(current)current.position[axis]=Number(input.value);el(`#${axis}-output`).textContent=Number(input.value).toFixed(2)})}el('#reset-model').addEventListener('click',resetModel);el('#reset-view').addEventListener('click',()=>{camera.position.set(1.9,1.45,2.25);orbit.target.set(0,.25,0);orbit.update()});el('#grid-toggle').addEventListener('change',e=>grid.visible=e.target.checked);el('#auto-rotate').addEventListener('change',e=>orbit.autoRotate=e.target.checked);el('#camera-view').addEventListener('change',e=>{const views={iso:[1.9,1.45,2.25],front:[0,.8,3],top:[0,3,.01],side:[3,.6,0]};camera.position.fromArray(views[e.target.value]);orbit.target.set(0,.25,0);orbit.update()});document.querySelectorAll('[data-model]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-model]').forEach(b=>b.classList.toggle('selected',b===button));load(button.dataset.model)}));
renderer.setAnimationLoop(()=>{orbit.update();renderer.render(scene,camera)});load('agv');
